#currently there is nothing here, but in the future maybe
# this is for configuring a wallpaper background
# you can do it with:
preload = /home/goldpaul/.config/hypr/archlinux.png
preload = /home/goldpaul/.config/hypr/arch1.png
wallpaper = eDP-1,/home/goldpaul/.config/hypr/archlinux.png
wallpaper = DP-2,/home/goldpaul/.config/hypr/arch1.png
wallpaper {
    monitor = eDP-1
    path = /home/goldpaul/.config/hypr/archlinux.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/goldpaul/.config/hypr/arch1.png

    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/fallback.jxl
    fit_mode = cover
}

# ...
