#currently there is nothing here, but in the future maybe
# this is for configuring a wallpaper background
# you can do it with:
preload = $HOME/media/Pictures/archlinux.png
preload = $HOME/media/Pictures/arch1.png
wallpaper = eDP-1,$HOME/media/Pictures/archlinux.png
wallpaper = DP-2,$HOME/media/Pictures/arch1.png
wallpaper {
    monitor = eDP-1
    path = $HOME/media/Pictures/archlinux.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = $HOME/media/Pictures/arch1.png

    fit_mode = cover
}
#do nothing
#wallpaper {
#    monitor = 
#    path = ~/fallback.jxl
#    fit_mode = cover
#}

